Portofolio Mobile Pull Request
mar4444/my-portofolio-2 pull request #1
Opened 2023-05-03 13:29 UTC by mar4444

This is the pull request of this project Portfolio. I have create branch with the name my-portofolio-mobile.
I created this project using html and css.

2023-05-03 14:52 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @mar4444, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 14:52 UTC, Qoosim commented on index.html
> +        </div>
- [ ] It is required to stick to the Figma design as close as possible. This involves font, color, padding, margin among others. Your design does not look the same as the Figma design. Kindly give a closer look to the Figma file and work your design alongside the Figma design. Take a look :point_down: 

### Your Design
![your-work-design](https://user-images.githubusercontent.com/26597432/235937162-ded279bf-9e59-465e-a026-e045434952b1.png)

### Figma Design
![temp-work-design](https://user-images.githubusercontent.com/26597432/235937191-3d174be8-11d0-4c30-9477-9deb61b3f703.png)

2023-05-03 14:52 UTC, Qoosim commented on index.html
> +    </section>
- [ ] It is required to stick to the Figma design as close as possible. This involves font, color, padding, margin among others. Your design does not look the same as the Figma design. Kindly give a closer look to the Figma file and work your design alongside the Figma design. Take a look :point_down: 

### Your Design
![your-about-section](https://user-images.githubusercontent.com/26597432/235945485-280d7409-9f6a-431e-9e3d-693a52f4e2f1.png)

### Figma Design

![temp-about-1](https://user-images.githubusercontent.com/26597432/235945606-1e201d79-7176-4dab-903c-3a034b8f7e4a.png)

![temp-about-2](https://user-images.githubusercontent.com/26597432/235945660-3a96d987-3ef6-4355-85bd-2bf847b521d4.png)

2023-05-04 12:27 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @mar4444, 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Well-implemented suggested changes.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-05-04 12:44 UTC, merged