Portofolio: Contact Me Project Pull Request
mar4444/my-portofolio-2 pull request #2
Opened 2023-05-09 14:12 UTC by mar4444

In this milestone I:

set up linters
updated README file
updated index.html
updated styles.css
Add a contact form
Create forms with HTML5 validations for UX and I:
Make sure that:
Name field accepts up to 30 chars.
Email field accepts only emails.
Message field accepts up to 500 chars.
All fields have placeholder text.
All fields have the correct type.
A user cannot submit the form if one or more of the fields is empty.

2023-05-09 15:12 UTC, usorfaitheloho requested changes
Hi @mar4444  :thumbsup:  ,

This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are still some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

## Highlights
- Good use of JavaScript, HTML&CSS best practices ✔️ 
-  Good collaboration with coding partner ✔️
- Followed the design for the contact from styling ✔️ 
<br/>
<br/>
<br/>

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 15:12 UTC, usorfaitheloho commented on index.html
> +                </label>
Great job in achieving some of the project requirements 😄 . According to the project requirement, all input fields should have the required attribute in order to activate the validation on submission. kindly implement the `required` attribute for the `textarea` field for your form 👍 

![image](https://github.com/mar4444/my-portofolio-2/assets/20537712/0787986e-4a25-4b04-8f40-31f5d08dc106)

2023-05-09 15:12 UTC, usorfaitheloho commented on style.css
> +}
According to the program requirement, you must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). From what you have in your design, the background image is not present in your contact form which might be because you didn't include the image in your images folder. Please try to fix the `background image` to enable you have a good design 😄 

Figma design :
![image](https://github.com/mar4444/my-portofolio-2/assets/20537712/9268db56-a807-41e9-933f-77b9a6a55f71)

Your design :
![image](https://github.com/mar4444/my-portofolio-2/assets/20537712/8412f7a5-a235-4e4c-9389-0df688c796b7)

2023-05-09 15:12 UTC, usorfaitheloho commented on style.css
> +  margin: 0 auto;
According to the program requirement, you must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) .Please use the font size given in the figma design to allow for consistency with your project 😄

2023-05-09 15:12 UTC, usorfaitheloho commented on style.css
> +}
Please you are to follow the guidelines for button interaction, the color you used for the `button: hover` is `background-color: #396df2` while the actual color in the Figma design is `background: #6070FF` 

![image](https://github.com/mar4444/my-portofolio-2/assets/20537712/4158a825-6461-40d9-a207-b3e65063ea98)

2023-05-10 14:28 UTC, taldr27 approved these changes
# Status: Approved! 🟢 
Hi team, @mar4444 @yayaismaail, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

## Highlights 🎉 
✅ Professional and customized README. 🤓
✅ Linters tests passing. 👍
✅ Correct use of GitHub Flow. 🙌
✅ Contact form is working fine. 💯
✅ Incorporates feedback from previous code reviewers. 🎯

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-05-10 14:34 UTC, merged